name: action-test
on:
  workflow_dispatch:
    inputs:
      distinct_id:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: echo distinct ID ${{ github.event.inputs.distinct_id }}
        run: echo ${{ github.event.inputs.distinct_id }}
      - name: ${{github.event.inputs.id}}
        run: echo run identifier ${{ inputs.id }}
      - name: Env vars
        env:
          cli-foo: ${{ github.event.client_payload.foo }}
          cli-bar: ${{ github.event.client_payload.bar }}
        run: |
         echo "Tenant-Name: ${cli-foo}"
         echo "Tenant-ID: ${cli-bar}"
