name: Execute Postman collection tests - Triggered event
 
on:
  repository_dispatch:
    types: [some_event]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone the repo
      uses: actions/checkout@v3
      
    - uses: actions/checkout@master
    - name: Execute tests
      uses: matt-ball/newman-action@master
      with:
         collection: petstore.postman_collection.json
         reporters: '["cli", "json"]'
    - name: Env vars
      env:
        cli-foo: ${{ github.event.client_payload.foo }}
        cli-bar: ${{ github.event.client_payload.bar }}
      run: |
       echo "Tenant-Name: ${cli-foo}"
       echo "Tenant-ID: ${cli-bar}"
