name: action-test

on:
  workflow_dispatch:
    inputs:
      foo:
      BAR:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: ${{github.event.inputs.id}}
        run: echo run identifier ${{ inputs.id }}
      - name: Env vars
        env:
          cli-foo: ${{ inputs.foo }}
          cli-bar: ${{ inputs.bar }}
        run: |
         echo "Tenant-Name: ${cli-foo}"
         echo "Tenant-ID: ${cli-bar}"
